name: Docker-Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies and build Docker image
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          docker build -t docker.pkg.github.com/${{ github.repository }}/aws-python-docker:latest .

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.DOCKER_AUTH_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Push Docker image
        run: docker push docker.pkg.github.com/${{ github.repository }}/aws-python-docker:latest
